import type { Metadata } from "next";
import localFont from "next/font/local";
import { UserProvider } from '../contexts/UserContext';
import { ProductProvider } from '../contexts/ProductContext';
import { StockProvider } from "@/contexts/StockContext";
import { BasketProvider } from '../contexts/BasketContext'; 
import { OrderProvider } from "@/contexts/OrderContext";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <UserProvider>
          <ProductProvider>
              <StockProvider>
                  <BasketProvider> 
                      <OrderProvider>
                          <html lang="en">
                              <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                                  {children}
                              </body>
                          </html>
                      </OrderProvider>
                  </BasketProvider>
              </StockProvider>  
          </ProductProvider>
      </UserProvider>  
  );
}
